backend/backend/urls.py
from django import views
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "",
        include("main.urls"),
    ),
    path("scraper/", include("scraper.urls")),
]

backend/main/urls.py
from django.urls import path, include
from . import views

app_name = "main"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("results/", views.ResultsView.as_view(), name="results"),
    path("scraper/", include("scraper.urls")),
]

backend/scraper/urls.py
from unicodedata import name
from django.urls import path

from . import views

app_name = "scraper"

urlpatterns = [
    path("source-process/", views.SourceScrape.as_view(), name="source-process"),
    path("twitter/<str:query>/", views.GetTwitter.as_view(), name="twitter"),
]

backend/main/models.py
import re
import nltk
import urllib
import requests
from nltk.sentiment import SentimentIntensityAnalyzer
from bs4 import BeautifulSoup


from django.db import models
from django.db.models.base import ModelState

nltk.download("vader_lexicon")


class SentimentCheck(models.Model):
    """Saving information about a URL request from the website"""

    created = models.DateTimeField(auto_now_add=True)
    url = models.CharField(max_length=200, null=True, blank=True)
    query = models.CharField(max_length=50, null=True, blank=True)
    messages_count = models.IntegerField(default=0)
    source = models.CharField(max_length=30, null=True, blank=True)
    sentiment = models.JSONField(default=dict)

    class Meta:
        verbose_name = "Sentiment check"
        verbose_name_plural = "Sentiment checks"

    def __str__(self) -> str:
        domain = urllib.parse.urlparse(self.url).netloc
        return f"Created: {self.created}. Root domain: {domain}"

    def get_page_text(self):
        html_doc = requests.get(self.url).content
        soup = BeautifulSoup(html_doc, "html.parser")
        for script in soup(["script", "style"]):
            script.extract()
        text = soup.get_text()
        return text

    def clean_text(self, text):
        text = (
            text.replace("\n", "").replace("\t", "").replace(":", "").replace(",", "")
        )
        # return re.findall(r'[A-Za-z]+', text)
        sentences = text.split(".")
        return sentences

    def get_sentiment(self, sentences: list):
        sia = SentimentIntensityAnalyzer()
        sentiments = []
        for sentence in sentences:
            senti_dict = sia.polarity_scores(sentence)
            sentiments.append(senti_dict)

        return sentiments

    def calculate_overall_sentiment(self):
        text = self.get_page_text()
        sentences = self.clean_text(text)
        sentiments = self.get_sentiment(sentences)

        negatice = 0.0
        neutral = 0.0
        positive = 0.0
        total = 0.0
        summary = dict()
        for senti in sentiments:
            negatice += senti["neg"]
            neutral += senti["neu"]
            positive += senti["pos"]
            total += senti["compound"]

        summary["negative"] = round((negatice / len(sentiments)) * 100)
        summary["neutral"] = round((neutral / len(sentiments)) * 100)
        summary["positive"] = round((positive / len(sentiments)) * 100)
        summary["total"] = round((total / len(sentiments)) * 100)
        return summary

backend/scraper/models.py
from django.db import models


class DataSource(models.Model):
    """Data source from which to scrape data"""

    name = models.CharField(max_length=20)
    url = models.CharField(max_length=200)
    active = models.BooleanField(default=True)

    def __str__(self) -> str:
        return f"{self.name}"

backend/main/views.py
import os
import requests
import logging
from django.contrib import messages
from django.shortcuts import redirect
from django.http import JsonResponse
from django.views.generic import TemplateView
from django.conf import settings
from nltk.sentiment.vader import SentiText

from .models import SentimentCheck

logger = logging.getLogger(__file__)

SCRAPER_API_URL = "http://scraper:8222"


class HomeView(TemplateView):
    """Main page"""

    template_name = "main/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        logger.info(f'>>>>> {os.environ.get("SQL_DATABASE", "UNDEFINED")=}')
        logger.info(f'>>>>> {os.environ.get("SQL_USER", "UNDEFINED")=}')
        logger.info(f'>>>>> {os.environ.get("SQL_PASSWORD", "UNDEFINED")=}')
        logger.info(f'>>>>> {os.environ.get("SQL_HOST", "UNDEFINED")=}')

        return context

    def post(self, request):
        try:
            query = request.POST.get("input_url")

            if "twitter_search" in request.POST:
                response = requests.get(SCRAPER_API_URL + f"/twitter/tweets/{query}")
                print(f"{response.json()=}")
                check = SentimentCheck.objects.create(query=query)
                check.sentiment = response.json()["tweets_sentiment"]
                check.source = "twitter"
                check.messages_count = response.json()["total_tweets"]
                check.save()
            elif "google_search" in request.POST:
                response = requests.get(SCRAPER_API_URL + f"/google/{query}")
                print(f"{response.json()=}")
                check = SentimentCheck.objects.create(query=query)
                check.sentiment = response.json()
                check.source = "google"
                check.save()
            elif "dailymotion_search" in request.POST:
                response = requests.get(SCRAPER_API_URL + f"/dailymotion/{query}")
                print(f"{response.json()=}")
                check = SentimentCheck.objects.create(query=query)
                check.sentiment = response.json()
                check.source = "dailymotion"
                check.save()
            elif "reddit_search" in request.POST:
                response = requests.get(SCRAPER_API_URL + f"/reddit/{query}")
                print(f"{response.json()=}")
                check = SentimentCheck.objects.create(query=query)
                check.sentiment = response.json()
                check.source = "reddit"
                check.save()
            else:
                check = SentimentCheck.objects.create(url=query)
                summary = check.calculate_overall_sentiment()
                check.sentiment = summary
                check.save()
        except Exception as e:
            logger.error(e)
            messages.error(request, "Failed processing the URL")
            return redirect(request.META["HTTP_REFERER"])

        return redirect("main:results")


class ResultsView(TemplateView):
    template_name = "main/results.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            check = SentimentCheck.objects.last()
            context["data"] = check
        except Exception as e:
            pass

        return context

    def post(self, request):
        try:
            check = SentimentCheck.objects.create(url=request.POST.get("input_url"))
            summary = check.calculate_overall_sentiment()
            check.sentiment = summary
            check.save()
        except Exception as e:
            messages.error(request, "Failed processing the URL")
            logger.error(e)
            return redirect(request.META["HTTP_REFERER"])

        return redirect(request.META["HTTP_REFERER"])

backend/scraper/views.py
from http.client import HTTPResponse
from django.http import JsonResponse
import requests
from django.db import reset_queries
from rest_framework.views import APIView
from rest_framework import permissions
from rest_framework.response import Response
from rest_framework import status

SCRAPER_API_URL = "http://localhost:8222"


class SourceScrape(APIView):

    permission_classes = [permissions.AllowAny]

    def post(self, request):
        print(f"Processing data source {request.data}...")
        return Response("ok", status=status.HTTP_200_OK)


class GetTwitter(APIView):
    permission_classes = [
        permissions.AllowAny,
    ]

    def get(self, request, query, **kwargs):
        response = requests.get(SCRAPER_API_URL + f"/twitter/tweets/{query}")
        return JsonResponse(response.json(), safe=False)

backend/main/templates/main/index.html
{% load static %}
<html>
  <head>
    <base href="/">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="author" content="colorlib.com">
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,800" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="{% static 'css/main.css' %}" rel="stylesheet" />
    <link rel="shortcut icon" href="{% static 'images/alarm.png' %}" type="image/x-icon">

    <!-- Charts JS -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.6.2/dist/chart.min.js"></script>

  </head>
  <body>
    <div class="s004">
      <form action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
        <fieldset>
          <legend>CHECK THE GENERAL SENTIENT AT:</legend>
          <div class="inner-form">
            <div class="input-field">
                <input name="input_url" class="input-url form-control" id="input_url" type="text" placeholder="Insert link to page..." required />
                <button type="submit" class="btn-search" name="url_search">
                <!-- <button type="button" onclick="calculateSentiment()" class="btn-search"> -->
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                    <path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"></path>
                  </svg>
                </button>
            </div>
          </div>
              {% for message in messages %}
            <div class="row">
              <div class="col-12 text-danger h4">
                {{message}}
              </div>
            </div>
          {% endfor %}
          <div class="suggestion-wrap">
             <span> <button class="btn btn-sm btn-primary" type="submit" name="twitter_search">Twitter</button></span>
             <span> <button class="btn btn-sm btn-primary" type="submit" name="dailymotion_search">Dailymotion</button></span>
             <span> <button class="btn btn-sm btn-primary" type="submit" name="google_search">Google</button></span>
             <span> <button class="btn btn-sm btn-primary" type="submit" name="reddit_search">Reddit</button></span>
          </div>
        </fieldset>
      </form>
    </div>
    <footer class="fixed-bottom">
      <!-- copyright -->
      <div class="copyright py-4 bg-danger text-white">
        <div class="container">
          <div class="row">
            <div class="col-sm-7 text-sm-left text-center">
              <p class="mb-0">Copyright
                <script>
                  var CurrentYear = new Date().getFullYear()
                  document.write(CurrentYear)
                </script> 
                © <a href="https://actappon.com" target="blank">Actappon</a></p>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  </body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

backend/main/templates/main/results.html
{% load static %}
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="author" content="colorlib.com">
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,800" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="{% static 'css/main.css' %}" rel="stylesheet" />

    <link rel="shortcut icon" href="{% static 'images/alarm.png' %}" type="image/x-icon">

    <!-- Charts JS -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.6.2/dist/chart.min.js"></script>
    <script src="https://use.fontawesome.com/d88301d9c6.js"></script>

  </head>
  <body>
    <div class="s004">
      <form action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
        <fieldset>
          <legend>Results</legend>
          <div class="suggestion-wrap">
            <a href="{% url 'main:home' %}"><span>Home <i class="fa fa-caret-right"></i></span></a>
            <!-- <span>Ladies</span>
            <span>Mens</span>
            <span>Accessories</span>
            <span>Sale</span> -->
          </div>
          <center>
              <h1> <b>{{ data.social_network }}</b> Sentiment Score:
                {% if data.sentiment.total > 0 %}
                    <b class="text-success">
                {% elif data.sentiment.total < 0 %}
                    <b class="text-danger">
                {% else %}
                    <b>
                {% endif %}
                        {{ data.sentiment.total }}%
                </b>
              </h1>
          </center>
          <div class="row">
              <div class="col-4 col-md-4">
                  {% if data.social_network %}
                    <h4>Messages count: {{ data.messages_count }}</h4>
                  {% else %}
                    <h4>Source: {{ data.source }} </h4>
                  {% endif %}
              </div>
              <div class="col-8 col-md-8">
                  <a href="{{ data.url }}" target="_blank">
                      {{ data.url }}
                  </a>
              </div>
          </div>
          <div class="row" >
              <canvas id="myChart" width="50vw" height="30vh"></canvas>
          </div>
          <div class="row">
              <div class="col-12 col-md-12">
                  <h3>Search Another</h3>
              </div>
          </div>
          <div class="inner-form">
              <div class="input-field">
                  <input name="input_url" class="input-url form-control" id="input_url" type="text" placeholder="Type to search..." required />
                  <button type="submit" class="btn-search">
                  <!-- <button type="button" onclick="calculateSentiment()" class="btn-search"> -->
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                      <path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"></path>
                    </svg>
                  </button>
              </div>
            </div>
            {% for message in messages %}
              <div class="row">
                <div class="col-12 text-danger h4">
                  {{message}}
                </div>
              </div>
            {% endfor %}

        </fieldset>  
        <hr>
    </form>
    
    </div>
    <footer class="fixed-bottom">
      <!-- copyright -->
      <div class="copyright py-4 bg-danger text-white">
        <div class="container">
          <div class="row">
            <div class="col-sm-7 text-sm-left text-center">
              <p class="mb-0">Copyright
                <script>
                  var CurrentYear = new Date().getFullYear()
                  document.write(CurrentYear)
                </script> 
                © <a href="https://actappon.com" target="blank">Actappon</a></p>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <script>
    const ctx = document.getElementById('myChart').getContext('2d');
    //Chart.defaults.font.size = 16;
    const myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: ["Positive", "Negative", "Neutral"],
            datasets: [{
                label: 'Sentiment Results',
                data: [{{ data.sentiment.positive }}, {{ data.sentiment.negative }}, {{ data.sentiment.neutral }}],
                backgroundColor: [
                    'green',
                    'red',
                    'rgba(54, 162, 235, 1)',
                ],
                borderColor: [
                    'green',
                    'red',
                    'rgba(54, 162, 235, 1)',
                ],
                borderWidth: 1
            }]
        },
        options: {
          plugins: {
            legend: {
              display: false,
              labels: {
                // This more specific font property overrides the global property
                font: {
                    size: 15
                }
              },
            },
              title: {
                display: true,
                text: 'Sentiment Summary',
                font: {
                  size: 25,
                  color: "#fff"
                }
              }
            },
          scales: {
            y: {
              ticks: {
                font: {
                  size: 16,
                  weight: "bold",
                  family:'Helvetica'
                },
                color: "black",
              }
            },
            x: {                
              ticks: {
                  font: {
                    size: 26,
                    family:'Helvetica'
                  },
                  color: "black",
                }
              }
            }
        }
    });
    </script>

    <script src="{% static 'js/extention/choices.js' %}"></script>
    <!-- <script>
      var textPresetVal = new Choices('#input_url',
      {
        removeItemButton: true,
      });

    </script> -->
    <!-- <script src="{% static 'js/main.js' %}"></script> -->
    <script>
      function calculateSentiment() {
        url = document.getElementById("input_url");
        check_sentiment_url = '{% url "main:home" %}';
        var formData = new FormData();
        formData.append('csrfmiddlewaretoken', '{{ csrf_token }}')
        formData.append('input_url', url)
    
        $.ajax({
            type: 'POST',
            url: check_sentiment_url,
            cache: false,
            processData: false,
            contentType: false,
            data: formData,
            enctype: 'multipart/form-data',
            success: function (response) {
                data = JSON.parse(JSON.stringify(response));
                alert(`Result: ${data.pos}`);
                //location.reload();
            },
            error: function (xhr, errmsg, err) {
                console.log(`ERROR: ${err}. Message: ${errmsg}. XHR: ${xhr}`)
                alert(`Failed calculation`)
            }
        })                
    }
    
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  </body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>